services:
  app:
    container_name: tech-challenge-payment-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
      - '5557:5557'
    env_file: .env
    environment:
      DATABASE_URL: 'mongodb+srv://mongodb:Senha%21123456tsdgdhh%24fgddfdffsvds@tc-payment-cluster.r5qwl.mongodb.net/tc-payment-db'
      API_PORT: 3333
    networks:
      - tech-challenge-payment-network
      - tech-challenge-global

networks:
  tech-challenge-payment-network:
    driver: bridge
  tech-challenge-global:
    external: true
