services:
  postgres:
    container_name: tech-challenge-payment-pg
    image: postgres
    ports:
      - '5439:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: tech-challenger
      PGDATA: '/var/lib/postgresql/data'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - tech-challenge-payment-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    container_name: tech-challenge-payment-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3333:3333'
      - '5555:5555'
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: 'postgresql://postgres:docker@postgres:5432/tech-challenger'
      API_PORT: 3333
    networks:
      - tech-challenge-payment-network

networks:
  tech-challenge-payment-network:
    driver: bridge

volumes:
  postgres-data:
