apiVersion: v1
kind: Service
metadata:
  name: prisma-studio-service
  namespace: tech-challenge-group-4
  labels:
    name: prisma-studio-service
spec:
  type: NodePort
  selector:
    app: prisma-studio
  ports:
    - name: prisma-studio-port
      protocol: TCP
      port: 5557
      targetPort: 5557
      nodePort: 31555
